// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "EarthRoot Cannabis",
  domain: "earthrootcannabis.ca",
  city: "Etobicoke",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-etobicoke",
  address: "5120 Dundas St W, Etobicoke, ON M9A 1C2",
  streetAddress: "5120 Dundas St W",
  postalCode: "M9A 1C2",
  phone: "(647) 382-5122",
  phoneIntl: "+16473825122",
  neighborhood: "Dundas St W / Islington / Etobicoke",
  nearbyAreas: ["Dundas St W", "Islington", "Six Points", "Kipling", "Bloor West", "Etobicoke Centre", "The Kingsway", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com/?q=5120+Dundas+St+W,+Etobicoke,+ON+M9A+1C2",
  mapEmbedUrl: "https://maps.google.com/maps?q=EarthRoot%20Cannabis%205120%20Dundas%20St%20W%2C%20Etobicoke%2C%20ON%20M9A%201C2&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6393",
  longitude: "-79.5372",
  hours: ["Open 24 Hours"],
  seoTitle: "EarthRoot Cannabis | Weed Dispensary in Etobicoke",
  metaDescription: "EarthRoot Cannabis is a local weed dispensary in Etobicoke offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Dundas St W", "Islington", "Six Points"],
  introVariant: "EarthRoot Cannabis is your welcoming neighborhood weed dispensary in Etobicoke, located at 5120 Dundas St W near Dundas St W / Islington / Etobicoke. We carry a massive selection of weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories for adults 19+. Conveniently located near Islington, our cannabis store and weed shop is designed to make finding the perfect strain easy and accessible.",
  neighborhoodDescription: "Located in the vibrant Dundas St W / Islington / Etobicoke district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking and local parking spaces are available nearby",
  transitNote: "Easily accessible via TTC bus and subway routes from nearby Kipling and Islington stations.",
  sectionTitle: "Serving Customers Near Dundas St W and Etobicoke Centre"
};
